### ISSUE TITLE
Blog Post for JCM

### ISSUE THREAD

**Issue by puneet0191** [joomla-projects/gsoc16_shareable-draft-content#1]
Get it reviewed from Mentors, Coordinate with Ana for Submissions

**Comment by nikitadhiman** [comment]
https://docs.google.com/document/d/16N89DJ-53a691PDQdnedHlU1DIH5iKw_nMmjy2AIfjg/edit?usp=sharing

**Comment by nikitadhiman** [comment]
This is the link for the first article. Let me know your views and I'll make the changes accordingly

**Comment by nikitadhiman** [comment]
http://magazine.joomla.org/issues/issue-june-2016/item/3055-shareable-draft-content
