### ISSUE TITLE
Create database schema for storing shared links

### ISSUE THREAD

**Issue by roland-d** [joomla-projects/gsoc16_shareable-draft-content#3]
Propose a database schema for storing the shared links and other needed values.
- [x] Define the fields to be used
- [x] Determine which field is the primary key field
- [x] Define the type of field
- [x] Create the SQL statement

**Comment by nikitadhiman** [comment]
@roland-d , article id should be the primary key field, as even when the article is updated after sharing it would still enable the use of same share link

**Comment by roland-d** [comment]
@nikitadhiman The article ID can't be the primary key because you can't control a primary key, this is an auto-increment value and controlled by the database.

**Comment by nikitadhiman** [comment]
For sharing purpose, a new field would be created containing the share link of the article. Initially, long share links would be stored in the db and later stage shortened link field can be introduced. 
Hence, for the fields required would be article_id, author_id (this would be useful while coding for draft manager, file_path, share_link. 
whenever the draft is shared the permission is 'read', thus no editing rights would be granted

**Comment by nikitadhiman** [comment]
https://github.com/joomla-projects/gsoc16_shareable-draft-content/pull/10/files 
Please review the files
